sudo: required

language: generic

services :
  - docker

before_install:
  - docker build -t sameerdk12/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true sameerdk12/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-2-774320013474"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"