sudo: required

language: generic

services :
  - docker

before_install:
  - docker build -t sameerdk12/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true sameerdk12/docker-react npm run test